In [14]:
import torch

In [15]:
import torch

# 创建输入张量
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 创建索引张量
index_tensor = torch.tensor([[0, 2], [1, 0], [2, 1]])
# 在维度 1 上进行 gather 操作
result = torch.gather(input_tensor, 1, index_tensor)
print("二维张量 gather 结果:", result)

二维张量 gather 结果: tensor([[1, 3],
        [5, 4],
        [9, 8]])


In [20]:
a=torch.ones(1,2,3)
b=torch.ones(2,2,3)

In [21]:
torch.cat([a,b],dim=0).shape

torch.Size([3, 2, 3])

In [22]:
torch.stack((a,b),dim=0).shape

RuntimeError: stack expects each tensor to be equal size, but got [1, 2, 3] at entry 0 and [2, 2, 3] at entry 1

In [5]:
x = torch.tensor([2,3,4,5],dtype=torch.float32)
x=x.softmax(dim=-1)
x

tensor([0.0321, 0.0871, 0.2369, 0.6439])

In [13]:
torch.multinomial(x,1)

tensor([3])

In [8]:
dim=5
torch.arange(0,dim,2)

tensor([0, 2, 4])

In [9]:

# 1.直接使用torch.outer函数
x = torch.tensor([2,3,4,5])
y = torch.tensor([2,2,2])
 
out = torch.outer(x,y)
print(out)


tensor([[ 4,  4,  4],
        [ 6,  6,  6],
        [ 8,  8,  8],
        [10, 10, 10]])


In [2]:
indexs=torch.tensor([2,1,0,3,2,1])

In [3]:
idx=indexs.argsort()
idx

tensor([2, 1, 5, 0, 4, 3])

In [4]:
c=indexs.bincount().numpy().cumsum(0)
c

array([1, 3, 5, 6], dtype=int64)

In [5]:
token_ids=idx//3
token_ids

tensor([0, 0, 1, 0, 1, 1])

In [9]:
start=3
end=5
exp_token_idx = token_ids[start:end]
exp_token_idx

tensor([0, 1])

In [12]:
t=None
c=3
a=t or ca'a'a'a'r'f'we'e
a

3

In [17]:
a=torch.ones(2,2)
shape=a.shape
torch.view_as_complex(a.reshape(*shape[:-1],-1,2)).shape

torch.Size([2, 1])

In [18]:
[None]*3

[None, None, None]

In [ ]:
每次输出预测的数据

In [21]:
logits=torch.tensor([[0.2,0.3,0.1,0.4]])

In [22]:
sorted_logits, sorted_indices = torch.sort(logits, descending=True, dim=-1)

In [23]:
sorted_logits

tensor([[0.4000, 0.3000, 0.2000, 0.1000]])

In [24]:
sorted_indices

tensor([[3, 1, 0, 2]])

In [29]:
import torch.nn.functional as F
sorted_probs = F.softmax(sorted_logits, dim=-1)
cumulative_probs = torch.cumsum(sorted_probs, dim=-1)
sorted_indices_to_remove = cumulative_probs > 0.7 #标记为False的是要保留的token
sorted_indices_to_remove[:, 1:] = sorted_indices_to_remove[:, :-1].clone() 
sorted_indices_to_remove

tensor([[False, False, False,  True]])

In [33]:
sorted_indices_to_remove[:, 0] = False
indices_to_remove = sorted_indices_to_remove.scatter(1, sorted_indices, sorted_indices_to_remove)
                # indices_to_remove = sorted_indices_to_remove[:,sorted_indices]=sorted_indices_to_remove上面代码与这句等价
indices_to_remove

tensor([[False, False,  True, False]])

In [34]:
logits[indices_to_remove] = -float('Inf')
logits

tensor([[0.2000, 0.3000,   -inf, 0.4000]])

In [32]:
input_ids_next = torch.multinomial(F.softmax(logits, dim=-1), num_samples=1)
            # torch.multinomial 函数用于从多项分布中进行抽样


In [ ]:
torch

In [37]:
seq=torch.ones(1,3)
seq

tensor([[1., 1., 1.]])

In [36]:
torch.full((1, 5 - seq.size(1)), 0)

tensor([[0, 0]])

In [ ]:
precompute_pos_cis(

In [20]:
q=torch.ones(1,2)
# k=torch.ones(1,2,2,1)
# v=torch.ones(1,2,2,1)
# q.tolist()
q

tensor([[1., 1.]])

In [16]:
q.mean(1).shape

torch.Size([1, 1, 1])

In [12]:
t=(q@k.transpose(-1,-2))
t.shape

torch.Size([1, 2, 1, 2])

In [13]:
z=t@v
z.shape

torch.Size([1, 2, 1, 1])

In [19]:
a=torch.ones((1,2))
a.shape

torch.Size([1, 2])

In [21]:
b=a.view(-1,1)
b.shape

torch.Size([2, 1])

In [4]:
past=(k,v)

In [6]:
k=torch.cat([past[0],k],dim=1)
v=torch.cat([past[0],v],dim=1)

In [7]:
k.shape

torch.Size([1, 4, 2, 2])

In [8]:
v.shape

torch.Size([1, 4, 2, 2])